# Generated by Django 5.1.6 on 2025-03-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Two Wheeler With Gear', 'Two Wheeler With Gear'), ('Two Wheeler WithOut Gear', 'Two Wheeler WithOut Gear'), ('Three Wheeler', 'Three heeler'), ('Four Wheeler', 'four wheeler')], max_length=50),
        ),
    ]
